- name: configure worker
  hosts: all
  tasks:
#    - name: groupadd docker
#      command: groupadd docker
#      ignore_errors: True
#      become: True
#      become-method: sudo
#      register: mymotd
    - name: usermod -aG docker $USER
      command: usermod -aG docker $USER
      ignore_errors: True
#      become: True
#      register: mymotd
    - name: newgrp docker
      command: newgrp docker
      ignore_errors: True
      
      
#      register: mymotd
#    - name: Hello Message
#      debug:
#        msg: "Hello World!"
#    - name: return motd to registered var
#      command: cat /etc/mc/sfs.ini
#      register: mymotd
#    - name: return value
#      debug:
#        msg: "The password is {{ mymotd }}"

