- name: configure worker
  hosts: all
#  strategy: debug
#  connection: ssh
  tasks:
     - name: Update all packages to their latest version
       become: True
       apt:
         name: "*"
         state: latest
         update_cache: yes
     - name: Install a list of packages
       apt:
         pkg:
         - mc
         - htop
         - qemu-guest-agent
         - docker
         - docker-compose
         - python3-pip
         state: latest
     - name: set timezone
       command: sudo timedatectl set-timezone Europe/Kiev
       become: True
     - name: Ensure group "docker" exists
       group:
         name: docker
         state: present
       become: True
     - name: Add the user mkorneyc to docker group
       user:
         name: mkorneyc
         groups: docker
         append: yes
       become: True
      
      
#      register: mymotd
#    - name: Hello Message
#      debug:
#        msg: "Hello World!"
#    - name: return motd to registered var
#      command: cat /etc/mc/sfs.ini
#      register: mymotd
#    - name: return value
#      debug:
#        msg: "The password is {{ mymotd }}"

