- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: return motd to registered var
      command: cat /etc/mc/sfs.ini
      register: mymotd


