- name: Hello World Sample
  hosts: all
  tasks:
    - name: return motd to registered var
#      command: sudo groupadd docker
      command: uname -a
      register: mymotd
#    - name: Hello Message
#      debug:
#        msg: "Hello World!"
#    - name: return motd to registered var
#      command: cat /etc/mc/sfs.ini
#      register: mymotd
    - name: return value
      debug:
        msg: "The password is {{ mymotd }}"

