  
- name: run grafana
  hosts: all
  tasks:
#     - name: run grafana
#       command: docker run -d -p 3000:3000 grafana/grafana
#       become: True
     - name: Create a grafana container
       docker_container:
         name: grafana
         image: grafana/grafana

